style(sbb-button): button disabled state [WIP]
sbb-design-systems/lyne-components pull request #2651
Opened 2024-05-13 07:34 UTC by DavideMininni-Fincons

## Preflight Checklist

- [ ] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [ ] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../docs/REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

-

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [ ] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-05-14 06:59 UTC, jeripeierSBB commented on src/components/core/styles/mixins/buttons.scss
> +  --sbb-button-border-width: #{functions.px-to-rem-build(1)};
```suggestion
  --sbb-button-border-width: var(--sbb-border-width-1x);
```

2024-05-14 07:25 UTC, jeripeierSBB requested changes

2024-05-14 07:25 UTC, jeripeierSBB commented on src/components/button/common/button-common.scss
> +  --sbb-button-border-style: dashed;
Could you please align the variables to the "system" used in button-common: there should be a variable for every state. Moreover, the border color should be smoke (so the current outcome doesn't look correct).

2024-05-14 07:53 UTC, mcilurzo commented
ux-review: the border color seems wrong. it sould be "smoke" in the default and negative variant.

2024-05-23 08:07 UTC, TomMenga approved these changes
Just a small thing.
The rest is lgtm 👍

2024-05-23 08:07 UTC, TomMenga commented on src/components/button/common/button-common.scss
> +  --sbb-button-color-disabled-border: var(--sbb-color-smoke);
```suggestion
```
I think it's not needed anymore

2024-05-23 14:33 UTC, mcilurzo commented
ux review: the border of the disabled state should be 1px

2024-05-24 09:03 UTC, mcilurzo approved these changes

2024-05-28 12:53 UTC, jeripeierSBB approved these changes
LGTM

2024-05-28 13:23 UTC, merged