feat(sbb-flip-card): first implementation
sbb-design-systems/lyne-components pull request #2946
Opened 2024-07-18 07:09 UTC by MarioCastigliano

## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/sbb-design-systems/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #2669 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../docs/REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- `sbb-flip-card` has been implemented
- `sbb-flip-card-summary` has been implemented
- `sbb-flip-card-details` has been implemented

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [x] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-07-18 09:27 UTC, DavideMininni-Fincons requested changes
Looks good, some minor point to fix

2024-07-18 09:27 UTC, DavideMininni-Fincons commented on src/elements/flip-card/flip-card-summary/flip-card-summary.stories.ts
> +export const Default: StoryObj = {
Maybe add another story with different alignment?

2024-07-18 09:27 UTC, DavideMininni-Fincons commented on src/elements/flip-card/flip-card-summary/flip-card-summary.ts
> +  @property({ attribute: 'image-alignment', reflect: true }) public imageAlignment:
Add type for values?

2024-07-18 09:27 UTC, DavideMininni-Fincons commented on src/elements/flip-card/flip-card/flip-card.ts
> +  }
```suggestion
  /** Returns the slotted sbb-flip-card-summary. */
  public get summary(): SbbFlipCardSummaryElement {
    return this.querySelector('sbb-flip-card-summary')!;
  }

  /** Returns the slotted sbb-flip-card-details. */
  public get details(): SbbFlipCardDetailsElement {
    return this.querySelector('sbb-flip-card-details')!;
  }

  /** Whether the card is flipped or not. */
  @state() private _flipped = false;

  private _language = new SbbLanguageController(this);

  /** Toggles the state of the sbb-flip-card. */
  public toggle(): void {
    this._flipped = !this._flipped;
    this.toggleAttribute('data-flipped', this._flipped);
    this.summary.inert = this._flipped;
    this.details.inert = !this._flipped;
  }
```

2024-07-18 09:27 UTC, DavideMininni-Fincons commented on src/elements/flip-card/flip-card/readme.md
> +It's meant to be used together with `sbb-flip-card-summary` and `sbb-flip-card-details`.
Add link to the components documentation

2024-07-18 09:27 UTC, DavideMininni-Fincons commented on src/elements/flip-card/flip-card/readme.md
> +The `sbb-flip-card` will switch to the flipped state after the user clicks on it or after the `toggle` method is called. Once the component is flipped, it will have the attribute `data-flipped`, whic
Not sure if the 'data-flipped' is really necessary for consumers..

2024-07-18 11:38 UTC, DavideMininni-Fincons commented on src/elements/flip-card/flip-card/readme.md
> +The `sbb-flip-card` will switch to the flipped state after the user clicks on it or after the `toggle` method is called. Once the component is flipped, it will have the attribute `data-flipped`, whic
we had some similar 'data-stuff' logic elsewhere.. not documented at all => not intended for use 😃

2024-07-18 11:56 UTC, kyubisation reviewed
Nice work! 😃 
I think there is one open topic that has not been addressed/implemented. The flip card should grow/shrink, depending on summary/details content size (e.g. with https://lyne-components-pr2946.app.sbb.ch/?path=/story/elements-sbb-flip-card-sbb-flip-card--long-content&globals=viewport:medium the summary state should be small and grow when switching to the details view). Maybe this can be achieved by just hiding/shrinking the inactive state?

2024-07-18 11:56 UTC, kyubisation commented on src/elements/flip-card/flip-card-details/flip-card-details.ts
> +      <div class="sbb-flip-card-details--wrapper">
Nitpick; Is the --wrapper part necessary? Usually the inner class just corresponds to the element name?

2024-07-18 11:56 UTC, kyubisation commented on src/elements/flip-card/flip-card-summary/flip-card-summary.scss
> +  width: 100%;
Nitpick; With the upcoming scss change, rules should not be separated by nested blocks, unless absolutely necessary.

2024-07-18 11:56 UTC, kyubisation commented on src/elements/flip-card/flip-card-summary/flip-card-summary.ts
> +      <div class="sbb-flip-card-summary--wrapper">
Nitpick; Same comment about --wrapper as above.

2024-07-18 11:56 UTC, kyubisation commented on src/elements/flip-card/flip-card/flip-card.scss
> +  flex-flow: wrap;
If the height is set on the host, the inner element does not grow with it. It should be enough to just add 100% height.
```suggestion
  height: 100%;
  flex-flow: wrap;
```

2024-07-18 11:56 UTC, kyubisation commented on src/elements/flip-card/flip-card/flip-card.ts
> +import '../../button/secondary-button.js';
Nitpick; I prefer to have the side-effect imports below the style import. What do you think?

2024-07-18 11:56 UTC, kyubisation commented on src/elements/flip-card/flip-card/flip-card.ts
> +export class SbbFlipCardElement extends LitElement {
Due to the slotchange event being used and chaning state of children, we should use the hydration mixin here.

2024-07-18 15:00 UTC, kyubisation reviewed
I think adding the two suggestions should solve the height issue.
The animation for this might not be perfect yet, but apparently there is still a discussion ongoing on how this should look anyway.

2024-07-18 15:00 UTC, kyubisation commented on src/elements/flip-card/flip-card-details/flip-card-details.scss
> +
```suggestion

:host([inert]) {
  display: none;
}

```

2024-07-18 15:00 UTC, kyubisation commented on src/elements/flip-card/flip-card-summary/flip-card-summary.scss
> +
```suggestion

:host([inert]) {
  display: none;
}

```
```

2024-07-19 07:17 UTC, florianstuerzinger commented
Animation does not yet meet the requirements:

Compared to the specification for the animation (https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?m=auto&t=tioFra6cD4BzsPNy-1), there are still various deviations. Please ensure the following:

**Duration:** Please ensure that duration and easing correspond to the specifications.

**Title:** The opacity of the title should fade to 0% when the card is clicked. So that the content and title do not overlap visually.
**Content:** The text is initially too far down. The movement should only be 8px.
**Content:** The text starts with an opacity of 0%
**Background:** The dark background starts in the position and size of the button and extends over the entire width and height when the card is clicked.
**Cover:** The hover effect is missing 
 
Extra: Is it possible to switch between the symbols in the button?

2024-07-19 07:18 UTC, florianstuerzinger commented
Button size S instead of L

2024-07-19 07:18 UTC, florianstuerzinger commented
Minimum height and above all independent of the content of the open state. 

Zero-Micro: 
* After, min-height 280px
* Below, min-height 280px

Small:
* After, min-height 240px
* Below, min-height 280px

Medium-Large:
* After, min-height 320px
* Below, min-height 320px

Wide-Ultra:
* After, min-height 400px
* Below, min-height 320px

2024-07-19 13:13 UTC, kyubisation commented
@florianstuerzinger Just a heads-up; The animation will not be perfect yet, but we will continue working on it and can fix that at a later date.

2024-07-19 15:07 UTC, kyubisation approved these changes
LGTM 👍

2024-07-19 15:42 UTC, kyubisation approved these changes
LGTM 👍 
Thanks again! 😃

2024-07-19 16:00 UTC, merged