feat(sbb-teaser-product): initial implementation [WIP]
sbb-design-systems/lyne-components pull request #2976
Opened 2024-07-31 07:36 UTC by TomMenga

## Preflight Checklist

- [ ] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [ ] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [pull request tracker](https://github.com/sbb-design-systems/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #2950

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../docs/REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- `sbb-teaser-product` initial implementation

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [ ] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-08-07 14:06 UTC, jeripeierSBB requested changes
nice work, fine tuning needed :)

2024-08-07 14:06 UTC, jeripeierSBB commented on src/elements/teaser-product/teaser-product-static/teaser-product-static.stories.ts
> +      <sbb-secondary-button style="margin-inline-start: var(--sbb-spacing-fixed-4x)"
I'd use an action group like in Figma instead of setting the spacing manually.

2024-08-07 14:06 UTC, jeripeierSBB commented on src/elements/teaser-product/teaser-product-static/teaser-product-static.ts
> + * Displays a text and a footnote, combined with an image, to tease a product
```suggestion
 * Displays a text and a footnote, combined with an image, to tease a product.
```

2024-08-07 14:06 UTC, jeripeierSBB commented on src/elements/teaser-product/teaser-product-static/teaser-product-static.visual.spec.ts
> +      <sbb-button>Label</sbb-button>
I'd use an action group with two buttons here (maybe static and not static visual regression tests are mixed somehow? )

2024-08-13 13:24 UTC, DavideMininni-Fincons commented on src/elements/teaser-product/common/teaser-product-common-element.ts
> +          <p class="sbb-teaser-product__footnote">
Replaced with span

2024-08-13 13:28 UTC, jeripeierSBB commented on src/elements/teaser-product/teaser-product/teaser-product.visual.spec.ts
> +    <sbb-title level="3" style="margin-block-start: 0;">Benefit from up to 70% discount</sbb-title>
I think the helper class could still be one to set margin to zero (also valid for sbb-title, and p).

Here the code from the lead-container:
`
::slotted(:is(sbb-breadcrumb-group, sbb-block-link).sbb-lead-container-spacing) {
  margin-block-end: var(--sbb-spacing-fixed-4x);
}

::slotted(:is(sbb-alert, sbb-alert-group).sbb-lead-container-spacing) {
  margin-block-end: var(--sbb-spacing-responsive-m);
}

::slotted(sbb-title.sbb-lead-container-spacing) {
  margin-block-start: 0;
}

::slotted(.sbb-lead-container-lead-text) {
  margin-block: 0 var(--sbb-spacing-responsive-s);
}
`

2024-08-14 14:51 UTC, jeripeierSBB approved these changes
LGTM, let's wait for the UX review

2024-08-15 16:15 UTC, merged