feat(sbb-time-input): add size 's'
sbb-design-systems/lyne-components pull request #3018
Opened 2024-08-22 13:47 UTC by TomMenga

This PR Closes #2769 

Most of the task was accomplished by the form field. 

The only doubt I have is on a CSS rule in `core.scss` that sets the max-width for time inputs. 
The value seems arbitrary and I could not find it in Figma. Might be that we need to tune it when sizing 's'
@jeripeierSBB Perhaps you know something more?

![image](https://github.com/user-attachments/assets/f2ad236f-822a-46dc-beb7-1eb23232369c)

2024-08-22 14:01 UTC, jeripeierSBB commented
@TomMenga for the size s, it would be 51px and from medium 58px. So we have a little problem here :D

2024-08-22 14:07 UTC, TomMenga commented
> @TomMenga for the size s, it would be 51px and from medium 58px. So we have a little problem here 

Not the best looking but something like this works. Ps. can I ask you where did you get the value?
![image](https://github.com/user-attachments/assets/58d631c9-24b1-4f4d-93db-36a3b54a75df)

2024-08-22 14:11 UTC, jeripeierSBB commented
@TomMenga  From Figma by clicking on the input:
<img width="155" alt="Bildschirmfoto 2024-08-22 um 16 09 15" src="https://github.com/user-attachments/assets/c74c49a9-2efc-4c9d-ab62-b2e8f8288f31">
<img width="179" alt="Bildschirmfoto 2024-08-22 um 16 09 10" src="https://github.com/user-attachments/assets/105ef182-ed1b-4ec3-ad27-e5f34e0ada79">


Maybe it's more clean, if we create a separate var for it and then only do the assignment in the block you showed? Would align a little bit more into the current solution

2024-08-22 14:42 UTC, TomMenga commented
> @TomMenga From Figma by clicking on the input: <img alt="Bildschirmfoto 2024-08-22 um 16 09 15" width="155" src="https://private-user-images.githubusercontent.com/29278232/360474254-c74c49a9-2efc-4c9d-ab62-b2e8f8288f31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzc3MDQsIm5iZiI6MTcyNDMzNzQwNCwicGF0aCI6Ii8yOTI3ODIzMi8zNjA0NzQyNTQtYzc0YzQ5YTktMmVmYy00YzlkLWFiNjItYjJlOGY4Mjg4ZjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0MzY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkOWJkNmU2N2U4YmJlOTliM2JkMDhjZTI4MGFmOWE0YTkxMTIxNTg2YzM1ZDU1YjIyNTE3MWUyODE5ZDA4NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hd62lZMgmurvNRcZNctWuhf30Gxtl5lP5j44z-2F92E"> <img alt="Bildschirmfoto 2024-08-22 um 16 09 10" width="179" src="https://private-user-images.githubusercontent.com/29278232/360474262-105ef182-ed1b-4ec3-ad27-e5f34e0ada79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzc3MDQsIm5iZiI6MTcyNDMzNzQwNCwicGF0aCI6Ii8yOTI3ODIzMi8zNjA0NzQyNjItMTA1ZWYxODItZWQxYi00ZWMzLWFkMjctZTVmMzRlMGFkYTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0MzY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmODFhNmExMjNjYmZlNTFhZDVhZGMyNjY2YzNlNjQ1YjBkYTEyMzZhZTI4NTYyYjQ1ZDI4MjgyNzU1YzgxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zycJHwU536Xbahdx-kdC5ehYaMFkfQoBxNFHCjJ_uwg">
> 
> Maybe it's more clean, if we create a separate var for it and then only do the assignment in the block you showed? Would align a little bit more into the current solution

Don't know how I missed it... I blame the holidays 😐

2024-08-23 07:42 UTC, DavideMininni-Fincons approved these changes
LGTM, the readme should be updated with a small note, as done in the sbb-select

2024-08-26 06:15 UTC, jeripeierSBB requested changes
Generally looks good, but screenshots are all using the same size.

2024-08-26 06:15 UTC, jeripeierSBB commented on src/elements/time-input/time-input.visual.spec.ts
>    const template = (args: Partial<ParamsType>): TemplateResult => html`
size needs to be respected. right now, all visual regression tests have the same size

2024-08-26 14:29 UTC, jeripeierSBB approved these changes
LGTM

2024-08-28 12:14 UTC, merged