feat(sbb-stepper): add size 's' [WIP]
sbb-design-systems/lyne-components pull request #3026
Opened 2024-08-26 13:21 UTC by TomMenga

This PR Closes #2765

2024-08-27 10:03 UTC, DavideMininni-Fincons approved these changes
I would add some test for the size change

2024-08-27 11:02 UTC, jeripeierSBB requested changes
LGTM, thank you! one docs change needed

2024-08-27 11:02 UTC, jeripeierSBB commented on src/elements/stepper/stepper/readme.md
> +| `size`           | `size`            | public  | `'s' \| 'm'`                     | `'m'`          | Size variant, either l or m.                                                      |
Description doesn't match possible values

2024-08-27 12:35 UTC, TomMenga commented
> I would add some test for the size change

Makes sense, I'll add them

2024-08-28 07:04 UTC, jeripeierSBB approved these changes
LGTM

2024-08-28 08:57 UTC, mcilurzo commented
UX Review: 

https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj?node-id=43627-137922#927954441
https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj?node-id=43627-137922#927952423

2024-08-28 13:28 UTC, mcilurzo commented
LGTM. Thank you!

2024-08-28 13:49 UTC, merged