refactor: replace [rtl] and [ltr] selectors with :dir
sbb-design-systems/lyne-components pull request #3084
Opened 2024-09-13 09:23 UTC by dauriamarco

Closes #3050

2024-09-16 14:06 UTC, TomMenga requested changes
Good job, some minor fixes

2024-09-16 14:06 UTC, TomMenga commented on src/elements/core/a11y/arrow-navigation.spec.ts
If the feedback  on `function getPrevAndNextKeys` is accepted, this file should be fine as it was before

2024-09-17 08:57 UTC, TomMenga approved these changes
LGTM 👍

2024-09-18 06:36 UTC, jeripeierSBB approved these changes
LGTM, thank you

2024-09-18 06:38 UTC, merged