feat: introduce button form support
sbb-design-systems/lyne-components pull request #3170
Opened 2024-10-23 15:14 UTC by jeripeierSBB

BREAKING CHANGE: Previously the `disabledInteractive` property had to be
used along with the `disabled` property.
With this change, either `disabled` or `disabledInteractive` should be used.

Closes #3043

2024-10-28 10:48 UTC, TomMenga requested changes
Good job 👍 
Just some doubts

2024-10-28 10:48 UTC, TomMenga commented on tools/manifest/custom-elements-manifest.config.js
I ask for a check from @DavideMininni-Fincons here

2024-10-28 11:08 UTC, jeripeierSBB commented on src/elements/button/common/primary-button.scss
> +:host(:not([disabled], :disabled, [disabled-interactive], :active, [data-active])) {
Yes, sadly, as it is used also with the link variant where :disabled never kicks in

2024-10-28 11:08 UTC, jeripeierSBB commented on src/elements/button/common/button-common.scss
> +:host(:not([disabled], :disabled, [disabled-interactive], :active, [data-active]):hover) {
agree, will check also other options to optimize

2024-10-28 11:09 UTC, jeripeierSBB commented on tools/manifest/custom-elements-manifest.config.js
Actually, it was Davide committing this changes :-)

2024-10-28 11:11 UTC, TomMenga commented on src/elements/button/common/primary-button.scss
> +:host(:not([disabled], :disabled, [disabled-interactive], :active, [data-active])) {
ah... true 😐

2024-10-29 08:55 UTC, DavideMininni-Fincons approved these changes
Except from Tom's comment about selector's improvement, it looks good.. thanks! :)

2024-10-30 09:57 UTC, TomMenga approved these changes
LGTM 👍

2024-10-31 14:19 UTC, kyubisation approved these changes
LGTM 👍

2024-10-31 14:22 UTC, merged