refactor(pearl-chain): implement new component structure
sbb-design-systems/lyne-components pull request #3172
Opened 2024-10-24 08:21 UTC by MarioCastigliano

## Preflight Checklist

- [ ] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [ ] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [pull request tracker](https://github.com/sbb-design-systems/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../docs/REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

-

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [ ] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-10-28 16:04 UTC, DavideMininni-Fincons reviewed
Partial review

2024-10-28 16:04 UTC, DavideMininni-Fincons commented on src/elements/pearl-chain/pearl-chain/pearl-chain.visual.spec.ts
> +import { html } from 'lit';
Forced colors tests?

2024-10-28 16:04 UTC, DavideMininni-Fincons commented on src/elements/pearl-chain/pearl-chain/pearl-chain.sample-data.ts
> +export function removeTimezone(time: SbbDateLike | null): Date | undefined {
I see this is used in the component ts file; having it in this file does not make sense to me

2024-11-13 13:41 UTC, jeripeierSBB requested changes
Thanks a lot for addressing the refactoring! I have some ideas and change requests. If you don't understand something, don't hesitate to ask me :). Some ideas or comments maybe cross other comments, depending on how we proceed with an idea.

2024-11-13 13:41 UTC, jeripeierSBB commented on src/elements/pearl-chain/pearl-chain-leg/pearl-chain-leg.scss
> +  z-index: 2;
We should try to implement it without z-index

2024-11-13 13:41 UTC, jeripeierSBB commented on src/elements/pearl-chain/pearl-chain-leg/pearl-chain-leg.scss
> +  z-index: 1;
We should try to implement it without z-index

2024-11-13 13:41 UTC, jeripeierSBB commented on src/elements/pearl-chain/pearl-chain-leg/pearl-chain-leg.scss
> +    :host([past='']) & {
```suggestion
    :host([past]) & {
```

2024-11-13 13:41 UTC, jeripeierSBB commented on src/elements/pearl-chain/pearl-chain-leg/pearl-chain-leg.scss
> +  background-color: currentcolor;
Basic question: why do you define color and then define background with currentcolor? as there is no text at all in this component, couldn't we directly style the background?

2024-11-13 13:41 UTC, jeripeierSBB commented on src/elements/pearl-chain/pearl-chain-leg/pearl-chain-leg.scss
> +  background-image: linear-gradient(to right, currentcolor 0%, currentcolor 50%, Canvas 50%);
Could you remove all Canvas or white background usages and replace them with another approach? I know it's not that easy, but I guess it should be possible. (e.g. with mask-image and linear gradient).

Using Canvas prints a white background:
<img width="1043" alt="Bildschirmfoto 2024-11-13 um 14 28 50" src="https://github.com/user-attachments/assets/b264206b-4228-4d77-8dd8-75fbc448a2ec">

2024-11-13 13:41 UTC, jeripeierSBB commented on src/elements/pearl-chain/pearl-chain-leg/pearl-chain-leg.scss
> +        z-index: 4;
as other comments, refactoring without z-index possible?

2024-11-13 13:41 UTC, jeripeierSBB commented on src/elements/pearl-chain/pearl-chain-leg/pearl-chain-leg.visual.spec.ts
> +describe('sbb-pearl-chain-leg', () => {
Should we also test combinations of props? like past and disruption and so on... so we ensure everyhing looks like expected.

2024-11-13 13:41 UTC, jeripeierSBB commented on src/elements/pearl-chain/pearl-chain-leg/pearl-chain-leg.visual.spec.ts
> +describe('sbb-pearl-chain-leg', () => {
I recommend to share the template either with cases and describeEach, or just a beforEach(). now e.g. every departure and arrival time is the same (times don't affect rendering right now)

2024-12-02 13:56 UTC, jeripeierSBB commented on src/elements/pearl-chain/pearl-chain/pearl-chain.stories.ts
> +  decorators: [(story) => html`<div style="max-width: 80%;">${story()}</div>`],
the old implementation was not always the best ;-) you can remove it.

2025-05-14 08:03 UTC, DavideMininni-Fincons requested changes
Needs some merge from master

2026-04-24 12:41 UTC, kyubisation commented
@MarioCastigliano After evaluating the use cases with the KIS division, we realized my previous specification would not work. I will create a new specification in the future and will close this PR for now. I sincerely apologize for letting this slide and wasting your effort. 🙇

2026-04-24 12:41 UTC, closed without merging