refactor(sbb-header)!: removed 'logo' slot
sbb-design-systems/lyne-components pull request #3230
Opened 2024-11-22 08:31 UTC by TomMenga

This PR Closes #3093

2024-11-22 11:38 UTC, kyubisation approved these changes
LGTM 👍

2024-11-22 11:38 UTC, kyubisation commented on src/elements/header/header/readme.md
> +- one or more action ([sbb-header-button](/docs/elements-sbb-header-sbb-header-button--docs) or [sbb-header-link](/docs/elements-sbb-header-sbb-header-link--docs))
```suggestion
- one or more actions ([sbb-header-button](/docs/elements-sbb-header-sbb-header-button--docs) or [sbb-header-link](/docs/elements-sbb-header-sbb-header-link--docs))
```

2024-11-22 11:38 UTC, kyubisation commented on src/elements/header/header/readme.md
> +By default, elements are aligned to the left. Use a `<div class="sbb-header-spacer">` to fill the empty space between elements.
```suggestion
Slotted elements are aligned to the left. Use `<div class="sbb-header-spacer">` to align elements after it to the right.
```

2024-11-25 08:38 UTC, DavideMininni-Fincons requested changes
Two tiny changes required

2024-11-25 08:38 UTC, DavideMininni-Fincons commented on src/elements/header/header/readme.md
> +Slotted elements are aligned to the left. Use `<div class="sbb-header-spacer">` to align elements after it to the right..
```suggestion
Slotted elements are aligned to the left. Use `<div class="sbb-header-spacer">` to align elements after it to the right.
```

2024-11-25 08:38 UTC, DavideMininni-Fincons commented on src/storybook/pages/home/home.stories.ts
> +      <a href="https://www.sbb.ch" class="sbb-header-class">
maybe "-logo" instead than "class"?

2024-11-25 08:56 UTC, TomMenga commented on src/storybook/pages/home/home.stories.ts
> +      <a href="https://www.sbb.ch" class="sbb-header-class">
whopsie

2024-11-25 09:11 UTC, DavideMininni-Fincons approved these changes

2024-11-25 14:31 UTC, jeripeierSBB commented on src/elements/header/header/header.ts
> + * @slot - Use the unnamed slot to add actions, content and logo to the header.
import of logo.js needs to be removed

2024-11-27 15:10 UTC, jeripeierSBB commented on src/elements/header/header/readme.md
> +  <div class="sbb-header-spacer sbb-header-spacer-logo"></div>
We don't need the header spacer here, logo should be enough? (would also apply to other files)
```suggestion
  <div class="sbb-header-spacer-logo"></div>
```

2024-11-28 07:58 UTC, merged