feat(date-input): create sbb-date-input as a native text input
sbb-design-systems/lyne-components pull request #3296
Opened 2024-12-13 09:02 UTC by kyubisation

This is an initial proof of concept for a custom text input.

2025-03-03 17:34 UTC, jeripeierSBB requested changes
Great work! I found some problems which should be checked. thank you :-)

2025-03-03 17:34 UTC, jeripeierSBB commented on src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
> +                  if (isDateInput(input)) {
also here we should probably have a test?

2025-03-03 17:34 UTC, jeripeierSBB commented on src/elements/datepicker/datepicker/datepicker.ts
> +      console.warn(
not sure whether we should wait with a warning? what if there is a blocker coming up for the new logic (doesn't hope so ;). but then they would have to change back.
the warning has the character of it should be fixed soonish for me.

2025-03-03 17:34 UTC, jeripeierSBB commented on src/elements/form-field/form-field/form-field.scss
> +.sbb-form-field__input ::slotted(:where(input, select, textarea, sbb-select, sbb-date-input)) {
@TomMenga little notice to you, that after merge your chip input PR needs an update regarding this :)

2025-03-03 17:34 UTC, jeripeierSBB commented on tools/docs/docs_generate.ts
> +        declaration.members.forEach((member) => {
nice addition :). shouldn't markdown be used? But it works with HTML, I know :-)

2025-03-05 14:13 UTC, kyubisation commented on tools/docs/docs_generate.ts
> +        declaration.members.forEach((member) => {
Unfortunately this did not work with markdown.

2025-03-05 14:14 UTC, kyubisation commented on src/elements/datepicker/datepicker/datepicker.ts
> +      console.warn(
Wait for what? Either we commit or we don't. Or what is your consideration?

2025-03-05 17:22 UTC, kyubisation commented on src/elements/date-input/date-input.ts
> +   *  previously set as the second argument to setFormValue.
This seems to be the case in all cases where this jsdoc is used. Should I adapt all of them?

2025-03-05 17:27 UTC, kyubisation commented on src/elements/datepicker/datepicker/datepicker.stories.ts
>  import { html, nothing, type TemplateResult } from 'lit';
Good find. That's weird...
Not sure if I should just apply a min-width?

2025-03-10 09:27 UTC, jeripeierSBB approved these changes
yipiieee

2025-03-10 09:27 UTC, jeripeierSBB commented on src/elements/core/styles/core.scss
> +  // This covers the plateholder of the sbb-date-input
```suggestion
  // This covers the placeholder of the sbb-date-input
```

2025-03-10 09:29 UTC, merged